### ISSUE TITLE
Program won't install

### ISSUE THREAD

**Issue by DeathToCountry** [Renno231/Gate-Dialing-System#2]
Tried installation based off instructions, received this message over multiple reboots and attempts

![2023-04-01_18 05 46](https://user-images.githubusercontent.com/16582184/229323576-a0ee6063-50af-4ed2-ae08-b3e38a8c9efb.png)

**Comment by Renno231** [comment]
Very strange. I'm working on rewriting the bin file, but I haven't been able to get results like those.

**Comment by Renno231** [comment]
Following up, I am unable to reproduce these results.
